server {
    listen 8080;
    server_name _;

    root /var/www/html;
    index index.php index.html;

    location ~ /\.git {
        deny all;
        return 404;
    }

    location / {
        try_files $uri $uri/ @php;
    }

    location @php {
        if (-f $document_root$uri.php) {
            rewrite ^(.*)$ $1.php last;
        }
        rewrite ^ /index.php?$query_string last;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}